config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :companies
  resources :employee_emails
  resources :employee_email_managers

  get "/employees/", to: 'employees#index', as: 'employee'

  get 'thankyou', to: 'quotes#thankyou', as: 'thankyou'

 

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :quotes, dependent: :destroy
end

app/models/employee_email.rb
class EmployeeEmail < ActiveRecord::Base
    validates :email, uniqueness: true
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  
  def index
    #THIS IS ACTING A NEW CONTROLLER WOULD, CREATING COMPANY ENTRY IN DATABASE
    @company = Company.new
  end

  def show
    @quotes = Quote.all
    if session[:employee_company_id] == nil
        @company = Company.find(params[:id])
        session[:employee_company_id] = @company.id
    else
        @company = Company.find(session[:employee_company_id])
    end

  end

  def new
    @companies = Company.all
  end

  def dashboard
    @companies = Company.all
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create

    @company = Company.new(company_params)
    if @company.save
      flash[:notice] = 'Your company information has been added'
      session[:current_company_id] = @company.id
      redirect_to new_quote_path
    else
      render action: 'index'
     end
  end

  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(company_params)
      flash[:notice] = 'Your company was updated'
      redirect_to employee_path
    else
      render action: 'new'
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to employee_path, notice: 'Company was successfully destroyed.' }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      if session[:employee_company_id] == nil
        @company = Company.find(params[:id])
        session[:employee_company_id] = @company.id
      else
        @company = Company.find(session[:employee_company_id])
      end
      #@company = Company.find(params[:id])
    end


    # Remember to update if/when company table has more columns added
    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:id, :email, :companyname, :name, :phone)
    end
end

app/controllers/employee_email_managers_controller.rb
class EmployeeEmailManagersController < ApplicationController


  def index
    @emails = EmployeeEmail.all
    @email = EmployeeEmail.new
  end

  # def show
  #   @email = EmployeeEmail.find(params[:id])
  # end

  def create
    @email = EmployeeEmail.new(email_params)

    if @email.save
      flash[:notice] = 'Your email information has been added'
      redirect_to employee_email_managers_path
    else
      render action: 'new'
     end
  end

  def destroy
    @email = EmployeeEmail.find(params[:id])
    if @email.present?
      @email.destroy
    end
    redirect_to employee_email_managers_path
  end

  private

    def email_params
      params[:employee_email].permit(:name, :email)
    end
end

app/controllers/employee_emails_controller.rb
# class EmployeeEmailsController < ApplicationController

#     def destroy
#         @email.destroy
#         respond_to do |format|
#             format.html { redirect_to employee_email_managers_path, notice: 'Line-item was successfully removed.' }
#         end
#     end
    
#     end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  #this is coppied directly from quotes_controller
  def index
    session[:employee_company_id] = nil
    @quotes = Quote.all
    @companies = Company.all
  end

  def show
    @quote = Quote.find[params[:id]]
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = Quote.all

  end

  def show
    @quotes = Quote.find(params[:company_id])
  end

  def new
    if session[:current_company_id] == nil
      redirect_to root_path
      flash[:notice] = 'You must fill out information about your company before continuing'
    end
    @quotes = Quote.all
    @quote = Quote.new
  end

  def edit
    @quote = Quote.find(params[:id])
    @company = @quote.company_id
  end

  def create
    @quote = Quote.new(quote_params)
    @quote.company_id = session[:current_company_id]
    @company = Company.find(session[:current_company_id])
    #session[:company_name] = @company.companyname
    if @quote.save
      flash[:notice] = 'Your quote information has been added'
      send_notification
      redirect_to thankyou_path
    else
      render action: 'new'
     end
  end

  def update
    @quote = Quote.find(params[:id])
    if @quote.update_attributes(quote_params)
      flash[:notice] = 'Your quote was updated'
      @company = @quote.company_id
      redirect_to company_path
    else
      render action: 'new'
    end
  end

  def destroy
    @quote.destroy
    @company = Company.find(session[:employee_company_id])
    respond_to do |format|
      format.html { redirect_to company_path, notice: 'Line-item was successfully removed.' }
    end
  end

  def thankyou
  end

  #Need to consider moving this method to a seperate helper method location and giving it a message for :text based on where the request comes from (e.g. Companies Controller or Quotes Controller). Keeping here for the time being because this is possibly the only use for notifications
  def send_notification
      @emails = EmployeeEmail.all
      if @emails == []
        return
      else
      #rather unwise to have my api key just sitting here in the code, need to check if a new api-key can be generated
      RestClient.post "https://api:key-5f4ada711a8a86a1292bcfe23aa9d0aa"\
      "@api.mailgun.net/v2/sandbox3fcc0ad1e9ee457da78753f228405f7e.mailgun.org/messages",
      :from => "Ovuline Advertising Notification System <mailgun@sandbox3fcc0ad1e9ee457da78753f228405f7e.mailgun.org>",
      :to => send_who_us,
      :subject => "Ovuline Advertising Site - A New Lead!",
      #ack! I need to find a way to get @company info into this next line
      :text => "This is the Ovuline Advertising Notification System test message! #{@company.companyname} company has submitted information for your inspection. View it at https://advertising-platform.herokuapp.com/employees"
      end
  end
    
  def send_who_us
    @emails = EmployeeEmail.all
    @who_array = []
    @emails.each do |f|
        @who_array << f.email
    end
    @who=""
    @who_array.each do |f|
        @who << "#{f}"
        #need to break this down to test it piece by piece
        if f != @who_array[-1]
            @who << ", "
        end
    end
    #this method finishes with this return instead of an end, could cause trouble if @who is ever incorrect
    return @who


end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params[:quote].permit(:id, :ad_type, :app_type, :mobile_platform, :budget, :company_id, :native_ad, :social_ad, :email_campaign, :ovuline_exclusive, :target_ttc, :target_preg, :target_sig_other, :target_1st_trim, :target_2nd_trim, :target_3rd_trim, :begin_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <center>
    <div class='make_text_white'>
      <table>
        <tr>
          <td>Name: </td>
          <td><%= f.text_field :name, :required => true %></td>
        </tr>

      <tr>
        <td>Company: </td>
        <td><%= f.text_field :companyname, :required => true %></td>
      </tr>
      <tr>
        <td>Email Address: </td>
        <td><%= f.email_field :email, :required => true %></td>
      </tr>
      <tr>
        <td>Phone: </td>
        <td><%= f.text_field :phone, :required => true %></td>
      </tr>
      </table>
    </div>
  </center>

  <div class = 'center_the_button'>
  <center><p><%= f.submit 'Advertise With Us!', :class => 'btn_advertise' %></p></center>
  </div>

<% end %>

app/views/companies/edit.html.erb
    <div class = 'fake_extended_nav'>
        <div class = 'navigation_bar_dashboard', class = 'sticky'> 
            <ul>
                <a href='/employees'><li>ALL QUOTES</li></a>
                <a href='/employee_email_managers'><li>NOTIFICATION MANAGER</li></a>
            </ul>
        </div>
    </div>
<div class="everything">
    <div class="section_teal">
       <div class="section_teal_padding">
           <h1>Editing Company</h1>

        <ul class="large-4 columns">
          <%= render 'form' %>
        </ul>
       </div>
    </div>
</div>
<%= link_to 'Back', employee_path %>

app/views/companies/index.html.erb
<!doctype html>
<html class="no-js" lang="en">

  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ovuline Advertising</title>
    <link rel="stylesheet" href="reset.css" />
    <link rel="stylesheet" href="style.css" />
  <!-- <script src="bower_components/modernizr/modernizr.js"></script> --> 
  </head>
  <body>
    <main class = "pageinfo">

          <!-- 1st Section -->
          <!-- <div class = 'fit_section_to_page'> -->
              <!-- <div id="topNav"> -->
                <div class = "navigation_bar_root">
                  <ul>
                    <a href="#howItWorks"><li>How It Works</li></a>
                    <a href="#services"><li>Services</li></a>
                    <a href="http://www.ovuline.com/"><img src="images/ovulineadvert.jpg"></a></li>
                    <a href="#audience"><li>Our Audience</li></a>
                    <a href="#design"><li>Design</li></a>
                  </ul>
                </div>

                <div class = 'sticky'>
                  <a class ='btn_advertise' href='quotes/new'>Advertise With Us!</a>
                </div>

                <% if notice %>
                <div class='section_pink_error'>
                  <p id="notice"><%= notice %></p>
                </div>
                <% end %>

                <!-- Background Image, 1st section -->
                  <div class = 'white_padding'>
                    <div class = 'special_size_img'>
                      <div class = 'move_it_forward_section'>
                        <!-- <h1>Get In Touch</h1> -->
                        <%= render 'form' %>

                       
                      </div>
                    </div>
                    
                  </div>

          
          <!-- </div> -->


                          <!--     HOW IT WORKS    -->    
          <div class="wrapper">
            <div id="howItWorks">
              <div id="top">
                  <img src="images/phone1.png" alt="Phone 1">
              </div>
              <div id="bottom">
                <div id="phone">
                  <img src="images/phone2.png" alt="Phone 2">
                </div>
                <h2>How It Works</h2>
                <ul class="flex-container">
                  <li class="flex-item">
                    <img src="images/workcircle1.png" alt="Work Circle 1" />
                    <p>Create custom content and ad assets</p>
                  </li>
                  <li class="flex-item">
                    <img src="images/workcircle2.png" alt="Work Circle 2" />
                    <p>Amplify exposure to assets accross multiple platforms (iOS and Android)</p>
                  </li>
                  <li class="flex-item">
                    <img src="images/workcircle3.png" alt="Work Circle 3" />
                    <p>Users engage with your ads</p>
                  </li>
                  <li class="flex-item">
                    <img src="images/workcircle4.png" alt="Work Circle 4" />
                    <p>Receive monthly reports on performance</p>
                  </li>
                </ul>    
              </div>
            </div>
          </div>

                              <!--     SERVICES    -->    
          <div class="wrapper">
            <div id="services">
              <div id="top">
                  <img src="images/phone3.png" alt="Phone 3">
              </div>
              <div id="bottom">
                <div id="phone">
                  <img src="images/phone4.png" alt="Phone 4">
                </div>
                <h2>Services</h2>
                <div class="text_root">
                    <h3>Social</h3>
                    <p>Ovia by Ovuline social media allows exposure to over 200,000 followers. Available on Twitter and Facebook.</p>
                    <h3>Ovia Exclusive</h3>
                     <p>Ovia has partnered with some of the best new brands and health partners to give users exclusive access to new products and promotions</p>
                    <h3>Native Advertisements</h3>
                     <p>No pop-ups, no banners, only original sponsored content that our users want to see. Ads are seamlessly integrated into the app’s newsfeed.</p>
                    <h3>Email Campaign</h3>
                     <p>Ovia Pregnancy and Ovia Fertility update emails are sent daily. Updates contain articles, quizzes and reminders to update information for my accurate results. </p>
                </div>
              </div>
              
            </div> 
          </div>
       

                        <!--     AUDIENCE    -->   
          <div class="wrapper"> 
            <div id="audience">
              <div id="top">
                  <img src="images/womanphone.png" alt="Woman With Phone">
              </div>
              <div id="bottom">
              <div id="phone">
                <img src="images/phone5.png" alt="Phone 5">
              </div>
                <h2>Our Audience</h2>
                <div class="image">
                  <img src="images/infograph1.png" alt="Audience Information">
                </div>
              </div>
              
            </div>
          </div>

                              <!--     DESIGN    -->    
          <div class="wrapper">
            <div id="design">
              <div id="top">
                  <img src="images/journal.png" alt="Journal">
              </div>
              <div id="bottom">
              <div id="phone">
                <img src="images/phone6.png" alt="Phone 6">
              </div>
                <h2>How We Design For You</h2>
                <ul class="flex-container">
                  <li class="flex-item">
                    <img src="images/miniads.png" alt="Ad Design" />
                    <p>Unlimited in-feed ad creative combination</p>
                  </li>
                  <li class="flex-item">
                    <img src="images/redpeople.png" alt="Connecting" />
                    <p>Optimized based on real-time engagement data</p>
                  </li>
                  <li class="flex-item">
                    <img src="images/magnifyglass.png" alt="Results" />
                    <p>Algorithims test ads to find the creative that works the best</p>
                  </li>
                </ul>    
                <ul class="flex-container">
                  <li class="flex-item">
                    <img src="images/1.png" alt="1" />
                    <p>Ovuline proposes ideas</p>
                  </li>
                  <li class="flex-item">
                    <img src="images/2.png" alt="2" />
                    <p>Initial Client Approval</p>
                  </li>
                  <li class="flex-item">
                    <img src="images/3.png" alt="3" />
                    <p>Ovuline creates drafts</p>
                  </li>
                </ul>
                <ul class="flex-container">
                  <li class="flex-item">
                    <img src="images/4.png" alt="4" />
                    <p>Client provides consolidated feedback</p>
                  </li>
                  <li class="flex-item">
                    <img src="images/5.png" alt="5" />
                    <p>Ovuline makes revisions and collects art from client</p>
                  </li>
                  <li class="flex-item">
                    <img src="images/6.png" alt="6" />
                    <p>Final client approval</p>
                  </li>
                </ul>
                <div class = 'bump_up'>   
                  <center>
                    <a class='btn_advertise' href='quotes/new'>Advertise Now!</a> 
                  </center>
                </div>
              </div>
            </div>
          </div>


        <footer>
           <img src="images/footerimg.jpg" alt="Ovuline Footer" />
        </footer>
      </div>
    </main>
  </body>
</html>

app/views/companies/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Advertise with Ovuline!</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/show.html.erb
<div class = 'companies_view_body'>
    <div class = 'fake_extended_nav'>
        <div class = 'navigation_bar_dashboard', class = 'sticky'> 
            <ul>
                <a href='/employees'><li>ALL QUOTES</li></a>
                <a href='/employee_email_managers'><li>NOTIFICATION MANAGER</li></a>
            </ul>
        </div>
    </div>

          <!--  <% if notice %>
                <div class='section_pink_error'>
                  <p id="notice"><%= notice %></p>
                </div>
            <% end %> -->

        <div class = "teal">
           <% if notice %>
                <div class='section_pink_error'>
                  <p id="notice"><%= notice %></p>
                </div>
            <% end %>
            <div class = 'float_it_left'>

                <tr><h1><%= @company.companyname %></h1> <p><strong>Contact Name: <%= @company.name %></strong></p>
                <p><strong> #: <%= @company.phone %></strong></p>
            </div>
        </div>

        <div class = 'section_pale_orange_thankyou'>
            <div class = 'section_general_show_custom'>
                    <table>
                        <tr>
                                <th><strong>Ad Type</strong></th>
                                <th><strong>Mobile Platform</strong></th>
                                <th>App Type</th>
                                <th>Campaign Beginning</th>
                                <th>Campaign Ending</th>
                                <th>Native Ad?</th>
                                <th>Article?</th>
                                <th>Ovuline Exclusive?</th>
                                <th>Email Campaign?</th>
                                <th>Target is TTC</th>
                                <th>Target is Pregnant</th>
                                <th>Target is significant other</th>
                                <th>Target is in first trimester</th>
                                <th>Target is in second trimester</th>
                                <th>Target is in third trimester</th>
                        </tr>
                        <% @quotes.each do |quote| %>
                                <% if quote.company_id == @company.id %>
                                <tr>

                                        <td><%= quote.ad_type %></td>
                                        <td><%= quote.mobile_platform %></td>
                                        <td><%= quote.app_type %></td>
                                        <td><%= quote.begin_date %></td>
                                        <td><%= quote.begin_date %></td>

                                        <td><%= quote.native_ad %></td>
                                        <td><%= quote.social_ad %></td>
                                        <td><%= quote.ovuline_exclusive %></td>
                                        <td><%= quote.email_campaign %></td>

                                        <td><%= quote.target_ttc %></td>
                                        <td><%= quote.target_preg %></td>
                                        <td><%= quote.target_sig_other %></td>
                                        <td><%= quote.target_1st_trim %></td>
                                        <td><%= quote.target_2nd_trim %></td>
                                        <td><%= quote.target_3rd_trim %></td>


                                        <td><%= link_to 'Remove', quote, method: :delete %></td>
                                        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
                                </tr>
                                <% end %>
                        <% end %>
                </table>
                <%= link_to 'Back', employee_path %>
            <!-- <div> -->
        </div>
</div>

app/views/employee_email_managers/_form.html.erb
<%= form_for @email, url: employee_email_managers_path do |f| %>
  <% if @email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email.errors.count, "error") %> prohibited this email from being saved:</h2>

      <ul>
      <% @email.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>Name
  <%= f.text_field :name %> </p>
  <!-- Input for :views needs to be contingent on :adtype or a number field -->
    <p>Email
  <%= f.email_field :email %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employee_email_managers/index.html.erb
<div class = 'navigation_bar_dashboard', class = 'sticky'> 
    <ul>
        <a href='/employees'><li>ALL QUOTES</li></a>
        <a href='/employee_email_managers'><li>NOTIFICATION MANAGER</li></a>
    </ul>
</div>


<div class = 'section_pale_orange_thankyou'>
    <div class = 'section_general'>

   <% if notice %>
                <div class='section_pink_error'>
                  <p id="notice"><%= notice %></p>
                </div>
            <% end %>

      <div class = 'dashboard_table'>
        <h1>Manage who gets email notifications</h1>
      </div>

      <center>
        <div class = 'dashboard_table'>
          <table>
            <thead>
              <tr>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                </tr>
              <% @emails.each do |email| %>

                <tr>
                  <td><%= email.name %></td>
                  <td><%= email.email %></td>
                  <td><%= link_to 'Delete', employee_email_manager_path(email), method: :delete %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </center>
      <br>
      <center>
          <%= render 'form' %>
      </center>
    </div>
  </div>

app/views/employee_email_managers/show.html.erb
<p>something</p>

app/views/employees/index.html.erb
<div class = 'navigation_bar_dashboard', class = 'sticky'> 
    <ul>
        <a href='/employees'><li>ALL QUOTES</li></a>
        <a href='/employee_email_managers'><li>NOTIFICATION MANAGER</li></a>
    </ul>
</div>

       <!--     <% if notice %>
                <div class='section_pink_error'>
                  <p id="notice"><%= notice %></p>
                </div>
            <% end %> -->

<div class = 'section_pale_orange_thankyou'>
    <div class = 'section_general'>

            <% if notice %>
                <div class='section_pink_error'>
                  <p id="notice"><%= notice %></p>
                </div>
            <% end %>
        <!-- <p id="notice"><%= notice %></p>
         -->
        <div class = 'dashboard_table'>

                <h1>Company Quotes</h1>


            <center>
                <table>
                        <tr>
                                <th>Contact Name</th>
                                <th>Company</th>
                                <th>Email</th>
                                <th>Phone</th>
                        </tr>
                        <% @companies.each do |company| %>
                                <tr>
                                        <td><%= company.name %></td>
                                        <td><%= company.companyname %></td>
                                        <td><%= company.email %></td>
                                        <td><%= company.phone %></td>
                                        <td><%= link_to "Edit", edit_company_path(company) %></td>
                                        <td><%= link_to "Show", company %></td>
                                        <td><%= link_to "Delete", company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                </tr>

                        <% end %>

                </table>
            </center>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OvulineAdCalc</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', employee_path %>

app/views/quotes/new.html.erb
                <div class = "navigation_bar_root">
                  <ul>
                    <a href="/companies#howItWorks"><li>How It Works</li></a>
                    <a href="/companies#services"><li>Services</li></a>
                    <a href="http://www.ovuline.com/"><img src="/images/ovulineadvert.jpg"></a></li>
                    <a href="/companies#audience"><li>Our Audience</li></a>
                    <a href="/companies#design"><li>Design</li></a>
                  </ul>
                </div>

<body class = 'pagequotes'>
        <%= render 'form' %>
</body>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>
<table>
        <tr>
                <td>Ad Type</td>
                <td>Number of Clicks</td>
                <td>Target Demographics</td>
                <td>Subtotal</td>
        </tr>
        <% @quotes.each do |quote| %>
                <tr>
                        <td><%= quote.adtype %></td>
                        <td><%= quote.views %></td>
                        <td><%= quote.demographics %></td>
                        <td><%= quote.subtotal %></td>
                        <td><%= link_to "Back",  %></td>
                        <td><%= link_to "Edit", edit_quote_path(quote) %></td>
                        <td><%= link_to "Delete", company, method: :delete %></td>
                </tr>
        <% end %>
</table>